name: simple_exif
description: "A web-enabled Flutter package for editing JPEG Exif information."
version: 0.0.1
repository: https://github.com/MasahideMori-SimpleAppli/simple_exif

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0